### ISSUE TITLE
Extension: Heuristic

### ISSUE THREAD

**Issue by karlback** [vonhachtaugust/shrdlite-course-project#6]
Implementation the heuristic (estimatedPathLength) to take the object forms and sizes into account when calculating the estimation

**Comment by MN5930** [comment]
I will work on this one too

**Comment by karlback** [comment]
Heuristic is pretty advanced at this point
- It´s definitely taking stack height into account, which is an [extension](http://chalmersgu-ai-course.github.io/shrdlite.html#extensions)
- Will extend it to take physical laws (object forms & sizes) into account if there is time left
